### PR TITLE
[UPDATE]Autogenerate up to date mavsdk proto plugins for Go

### PR DESCRIPTION
**Pull request by Tee-Stark**
Ran auto-generate scripts for the up-to-date plugins and features of MAVSDK. Go wrapper is now up to date with newer plugins from the main MAVSDK-proto repository.

### CODE REVIEW

**Review by julianoes — COMMENTED** [review]
I think this is good but you might also want to update/commit the proto submodule, so that it matches the sources.

**Comment by Tee-Stark** [comment]
> I think this is good but you might also want to update/commit the proto submodule, so that it matches the sources.

Oh! okay, so I used the actual up-to-date proto files from the submodule repository @ [https://github.com/mavlink/MAVSDK-Proto/tree/5cb33bbe09bae83105a2eff915a09e3438e9033f](https://github.com/mavlink/MAVSDK-Proto/tree/5cb33bbe09bae83105a2eff915a09e3438e9033f). From what I see, I don't need to push any updates anymore on that part. Or is there anything different I don't know?🤔

**Comment by Tee-Stark** [comment]
I think I figured it now, I discovered I wasn't using the latest changes from the main branch of the proto repository. I have regenerated the sources and now it is up to date. I'll be glad if you can confirm that @julianoes

**Comment by julianoes** [comment]
Actually, you might want to use the `v1.4` branch of proto, that way you're not affected by the `v2.0` work.

**Comment by Tee-Stark** [comment]
Oh alright, I'll switch to that now and push the new updates. Thanks

**Comment by Tee-Stark** [comment]
I can see here that there is a `v1.4log-files-fix` branch which is more up to date than the `v1.4`, do you recommend I use it?

**Comment by julianoes** [comment]
That's a special fix only required for Python and Java.

**Review by julianoes — APPROVED** [review]

**Comment by ykhedar** [comment]
Looks good, thanks for the PR @Tee-Stark :)

**Pull request merged**
